/**
 * check-source-registry — validates the central source registry and writes an
 * inspectable report. No browser: it builds the registry from the audit model +
 * the regulatory feed and confirms every entry has a stable id and a resolved
 * destination (internal target and/or external URL).
 *
 *   npm run check:registry
 */
import { writeFileSync, mkdirSync } from 'node:fs'
import { buildSourceRegistry, type SourceRef } from '@/lib/sourceRegistry'

function hasInternalTarget(r: SourceRef): boolean {
  return !!(r.internalTargetCellKey || r.internalTargetRowKey || r.internalTargetSectionId)
}
function hasExternal(r: SourceRef): boolean {
  return !!(r.externalUrl || r.externalPdfUrl)
}

function main() {
  const reg = buildSourceRegistry()
  const auditCells = reg.filter((r) => r.sourceType === 'audit_cell')
  const regItems = reg.filter((r) => r.sourceType === 'regulatory_item')
  const missingId = reg.filter((r) => !r.sourceId)
  const internalNoTarget = reg.filter((r) => r.isInternal && !hasInternalTarget(r))
  const externalOnly = reg.filter((r) => !r.isInternal && hasExternal(r))
  const withExternalBackup = reg.filter((r) => r.isInternal && hasExternal(r))

  const L: string[] = []
  L.push('# Source registry', '')
  L.push('_Generated by `npm run check:registry`. Every source link maps to one entry here — a stable `sourceId` and an explicit internal target and/or external document._', '')
  L.push('## Summary', '', '| Metric | Count |', '| --- | ---: |')
  L.push(`| Total source references | ${reg.length} |`)
  L.push(`| · Data-Audit cells (internal) | ${auditCells.length} |`)
  L.push(`| · Regulatory feed items (internal) | ${regItems.length} |`)
  L.push(`| Internal refs with an external document too | ${withExternalBackup.length} |`)
  L.push(`| External-only refs | ${externalOnly.length} |`)
  L.push(`| **Missing sourceId** | **${missingId.length}** |`)
  L.push(`| **Internal refs with no resolvable target** | **${internalNoTarget.length}** |`, '')

  L.push('## Field coverage (regulatory items carry provenance)', '')
  L.push('| Field | Regulatory items with it |', '| --- | ---: |')
  for (const f of ['sourceDate', 'surfacedAt', 'reasonShownToday', 'internalTargetSectionId', 'internalTargetRowKey', 'externalUrl'] as const) {
    L.push(`| ${f} | ${regItems.filter((r) => (r as Record<string, unknown>)[f] != null).length} / ${regItems.length} |`)
  }
  L.push('')

  L.push('## Sample regulatory entries', '', '| sourceId | tab | month | rowKey | sourceDate | surfacedAt | external |', '| --- | --- | --- | --- | --- | --- | --- |')
  for (const r of regItems.slice(0, 8)) {
    L.push(`| ${r.sourceId} | ${r.internalTargetTab ?? ''} | ${r.internalTargetSectionId ?? ''} | ${r.internalTargetRowKey ?? ''} | ${r.sourceDate ?? ''} | ${r.surfacedAt ?? ''} | ${(r.externalUrl || r.externalPdfUrl || '').slice(0, 40)} |`)
  }
  L.push('')

  mkdirSync('docs', { recursive: true })
  writeFileSync('docs/source-registry.md', L.join('\n'))

  console.log('── Source registry ───────────────────────────────────────────')
  console.log(`Total refs:            ${reg.length}  (audit cells ${auditCells.length}, regulatory ${regItems.length})`)
  console.log(`Internal + external:   ${withExternalBackup.length}   ·   External-only: ${externalOnly.length}`)
  console.log(`Missing sourceId:      ${missingId.length}`)
  console.log(`Internal, no target:   ${internalNoTarget.length}`)
  console.log('Report:                docs/source-registry.md')
  console.log('──────────────────────────────────────────────────────────────')

  if (missingId.length || internalNoTarget.length) {
    console.error(`\n✗ registry has ${missingId.length} id-less and ${internalNoTarget.length} target-less internal refs.`)
    process.exit(1)
  }
  console.log('\n✓ Every source reference has a stable id and a resolvable destination.')
}

main()
